name: PR Branch Checker

on:
  pull_request:

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: testing runs
        run: |
          git fetch
          # git checkout test
          # git checkout main
          git diff --name-only test
      # - name: Conditional step for main
      #   if: ${{ github.event.pull_request.base.ref == 'test' }}
      #   run: |
      #     if git diff --name-only "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF" \
      #     | grep -qE '^\.changeset(/|$)|^CHANGELOG\.md$'; then
      #       echo "✅ All good"
      #     else
      #       echo "❌ Looks like you forgot to run changeset versioning"
      #       exit 1
      #     fi
