name: PR Branch Checker

on:
  pull_request:

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: testing runs
        if: ${{ github.event.pull_request.base.ref == 'test' }}
        run: |
          git fetch
          git checkout "$GITHUB_BASE_REF" 
          git checkout "$GITHUB_HEAD_REF"
          git diff --name-only "$GITHUB_BASE_REF"
          if git diff --name-only "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF" \
          | grep -qE '^\.changeset(/|$)|^CHANGELOG\.md$'; then
            echo "✅ All good"
          else
            echo "❌ Looks like you forgot to run changeset versioning"
            exit 1
          fi
