name: PR Branch Checker

on:
  pull_request:

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - name: Determine target branch
        run: |
          echo "Head branch: $GITHUB_HEAD_REF"
          echo "Base branch: $GITHUB_BASE_REF"
      - name: Conditional step for main
        if: ${{ github.event.pull_request.base.ref == 'test' }}
        run: echo "This PR targets test branch"
