name: PR Branch Checker

on:
  pull_request:

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - name: testing runs
        run: |
          git diff --name-only "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF"
      - name: Conditional step for main
        if: ${{ github.event.pull_request.base.ref == 'test' }}
        run: |
          if git diff --name-only "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF" \
          | grep -qE '^\.changeset(/|$)|^CHANGELOG\.md$'; then
            echo "✅ All good"
          else
            echo "❌ Looks like you forgot to run changeset versioning"
            exit 1
          fi
